name: Automated Daily Commit
on:
  schedule:
    - cron: "0 8 * * *"  # Runs once a day at 1:30 PM IST

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make a commit
        run: |
          date >> log.txt  # Append the current date to a file
          git config --global user.email "tusharkant306@gmail.com"
          git config --global user.name "Kant99"
          git add log.txt
          git commit -m "Automated commit: $(date)"
          git push
